exec_once:
 execs:
  Get orocrm source:
   name: Get orocrm source
   command: |
     wget -qcO- https://github.com/oroinc/crm-application/archive/2.6.1.tar.gz  | tar xvz  -C . --strip 1
  Run composer install:
   name: Run composer install
   timeout: 1000
   command: |
     #!/usr/bin/env bash
     export COMPOSER_HOME=/usr/local/bin/.composer 
     /usr/local/bin/composer install --no-interaction
post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/orocrm
     service apache2 restart
